-- Bode Andarilho PWA v2
-- Esta migration é aditiva e deliberadamente não toca nas tabelas legadas.
-- Aplicar somente em um ambiente isolado após validação pelo Supabase CLI.

create schema if not exists pwa_v2;
create schema if not exists pwa_private;

revoke all on schema pwa_v2 from public;
grant usage on schema pwa_v2 to anon, authenticated, service_role;

revoke all on schema pwa_private from public;
grant usage on schema pwa_private to authenticated, service_role;

create table if not exists pwa_v2.perfis (
    id uuid primary key default extensions.gen_random_uuid(),
    auth_user_id uuid unique references auth.users(id) on delete set null,
    nome text not null check (char_length(btrim(nome)) between 2 and 160),
    email text not null check (position('@' in email) > 1),
    telefone text,
    status text not null default 'active'
        check (status in ('invited', 'pending', 'active', 'suspended')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists perfis_email_lower_uidx
    on pwa_v2.perfis (lower(email));

create table if not exists pwa_v2.identidades_externas (
    id bigint generated by default as identity primary key,
    perfil_id uuid not null references pwa_v2.perfis(id) on delete cascade,
    provedor text not null check (provedor in ('telegram', 'whatsapp', 'instagram', 'outro')),
    external_user_id text not null check (char_length(btrim(external_user_id)) between 1 and 240),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (provedor, external_user_id),
    unique (perfil_id, provedor)
);

create table if not exists pwa_v2.lojas (
    id bigint generated by default as identity primary key,
    nome text not null check (char_length(btrim(nome)) between 2 and 180),
    slug text not null check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    numero_loja text,
    descricao text,
    cidade text,
    uf text check (uf is null or char_length(uf) between 2 and 3),
    endereco text,
    rito text,
    potencia text,
    potencia_complemento text,
    instagram_handle text,
    logo_path text,
    template_card_path text,
    layout_config jsonb not null default '{}'::jsonb,
    status text not null default 'active'
        check (status in ('draft', 'active', 'archived')),
    created_by uuid references pwa_v2.perfis(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (slug)
);

create table if not exists pwa_v2.vinculos_loja (
    id bigint generated by default as identity primary key,
    perfil_id uuid not null references pwa_v2.perfis(id) on delete cascade,
    loja_id bigint references pwa_v2.lojas(id) on delete cascade,
    papel text not null check (papel in ('member', 'secretary', 'admin')),
    status text not null default 'active'
        check (status in ('invited', 'active', 'inactive')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (loja_id is not null or papel = 'admin'),
    unique (perfil_id, loja_id, papel)
);

create unique index if not exists vinculos_admin_global_uidx
    on pwa_v2.vinculos_loja (perfil_id)
    where loja_id is null and papel = 'admin';

create table if not exists pwa_v2.convites_conta (
    id uuid primary key default extensions.gen_random_uuid(),
    token_hash text not null unique,
    email_autorizado text not null check (position('@' in email_autorizado) > 1),
    papel text not null check (papel in ('member', 'secretary', 'admin')),
    loja_id bigint references pwa_v2.lojas(id) on delete cascade,
    valid_until timestamptz not null,
    consumed_at timestamptz,
    consumed_by_profile_id uuid references pwa_v2.perfis(id) on delete set null,
    created_by_profile_id uuid references pwa_v2.perfis(id) on delete set null,
    created_at timestamptz not null default now(),
    check (loja_id is not null or papel = 'admin'),
    check ((consumed_at is null) = (consumed_by_profile_id is null))
);

create table if not exists pwa_v2.eventos (
    id bigint generated by default as identity primary key,
    loja_id bigint not null references pwa_v2.lojas(id) on delete restrict,
    criado_por_id uuid not null references pwa_v2.perfis(id) on delete restrict,
    secretario_id uuid references pwa_v2.perfis(id) on delete set null,
    secretario_snapshot_nome text,
    evento_at timestamptz not null,
    titulo text not null check (char_length(btrim(titulo)) between 2 and 160),
    descricao text,
    status text not null default 'draft'
        check (status in ('draft', 'published', 'cancelled', 'closed')),
    visibilidade text not null default 'private'
        check (visibilidade in ('private', 'public')),
    public_token_hash text not null unique,
    idempotency_key_hash text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (loja_id, idempotency_key_hash)
);

create table if not exists pwa_v2.solicitacoes_presenca (
    id bigint generated by default as identity primary key,
    evento_id bigint not null references pwa_v2.eventos(id) on delete cascade,
    perfil_id uuid references pwa_v2.perfis(id) on delete set null,
    visitante_nome text not null check (char_length(btrim(visitante_nome)) between 2 and 160),
    visitante_email text,
    visitante_telefone text,
    agape text not null default 'sem' check (agape in ('sem', 'com', 'gratuito', 'pago')),
    status text not null default 'pending'
        check (status in ('pending', 'approved', 'rejected', 'cancelled')),
    origem text not null default 'public'
        check (origem in ('public', 'pwa', 'telegram', 'admin')),
    idempotency_key_hash text not null,
    recibo_hash text not null unique,
    revisado_por_id uuid references pwa_v2.perfis(id) on delete set null,
    revisado_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (evento_id, idempotency_key_hash),
    check (visitante_email is null or position('@' in visitante_email) > 1)
);

create table if not exists pwa_v2.publicacoes_canal (
    id bigint generated by default as identity primary key,
    evento_id bigint not null references pwa_v2.eventos(id) on delete cascade,
    artefato_path text,
    canal text not null check (canal in ('instagram', 'whatsapp', 'telegram')),
    estado text not null default 'prepared'
        check (estado in ('prepared', 'share_initiated', 'confirmed_by_user', 'api_published', 'failed')),
    evidencia_externa_url text,
    evidencia_externa_id text,
    erro text,
    idempotency_key_hash text not null,
    criado_por_id uuid references pwa_v2.perfis(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (evento_id, canal, idempotency_key_hash)
);

create table if not exists pwa_v2.auditoria (
    id bigint generated by default as identity primary key,
    ator_perfil_id uuid references pwa_v2.perfis(id) on delete set null,
    acao text not null check (char_length(btrim(acao)) between 2 and 120),
    entidade_tipo text not null check (char_length(btrim(entidade_tipo)) between 2 and 80),
    entidade_id text,
    origem text not null check (origem in ('pwa', 'telegram', 'public', 'scheduler', 'bootstrap', 'system')),
    request_id uuid,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

-- Índices de todas as FKs, inclusive as que também possuem índices de unicidade.
create index if not exists identidades_externas_perfil_idx on pwa_v2.identidades_externas (perfil_id);
create index if not exists lojas_created_by_idx on pwa_v2.lojas (created_by);
create index if not exists vinculos_loja_perfil_idx on pwa_v2.vinculos_loja (perfil_id);
create index if not exists vinculos_loja_loja_idx on pwa_v2.vinculos_loja (loja_id);
create index if not exists convites_conta_loja_idx on pwa_v2.convites_conta (loja_id);
create index if not exists convites_conta_consumed_by_idx on pwa_v2.convites_conta (consumed_by_profile_id);
create index if not exists convites_conta_created_by_idx on pwa_v2.convites_conta (created_by_profile_id);
create index if not exists eventos_loja_idx on pwa_v2.eventos (loja_id);
create index if not exists eventos_criado_por_idx on pwa_v2.eventos (criado_por_id);
create index if not exists eventos_secretario_idx on pwa_v2.eventos (secretario_id);
create index if not exists solicitacoes_presenca_evento_idx on pwa_v2.solicitacoes_presenca (evento_id);
create index if not exists solicitacoes_presenca_perfil_idx on pwa_v2.solicitacoes_presenca (perfil_id);
create index if not exists solicitacoes_presenca_revisado_por_idx on pwa_v2.solicitacoes_presenca (revisado_por_id);
create index if not exists publicacoes_canal_evento_idx on pwa_v2.publicacoes_canal (evento_id);
create index if not exists publicacoes_canal_criado_por_idx on pwa_v2.publicacoes_canal (criado_por_id);
create index if not exists auditoria_ator_idx on pwa_v2.auditoria (ator_perfil_id);
create index if not exists eventos_loja_evento_at_idx on pwa_v2.eventos (loja_id, evento_at desc);
create index if not exists presencas_evento_status_idx on pwa_v2.solicitacoes_presenca (evento_id, status, created_at);

create or replace function pwa_private.current_profile_id()
returns uuid
language sql
stable
security definer
set search_path = pwa_v2, pg_catalog
as $$
    select p.id
      from pwa_v2.perfis as p
     where p.auth_user_id = auth.uid()
     limit 1
$$;

create or replace function pwa_private.is_global_admin()
returns boolean
language sql
stable
security definer
set search_path = pwa_v2, pg_catalog
as $$
    select exists (
        select 1
          from pwa_v2.vinculos_loja as v
         where v.perfil_id = pwa_private.current_profile_id()
           and v.loja_id is null
           and v.papel = 'admin'
           and v.status = 'active'
    )
$$;

create or replace function pwa_private.has_store_role(target_store_id bigint, allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = pwa_v2, pg_catalog
as $$
    select pwa_private.is_global_admin()
        or exists (
            select 1
              from pwa_v2.vinculos_loja as v
             where v.perfil_id = pwa_private.current_profile_id()
               and v.loja_id = target_store_id
               and v.papel = any(allowed_roles)
               and v.status = 'active'
        )
$$;

create or replace function pwa_private.consume_invite(
    invite_token_hash text,
    target_auth_user_id uuid,
    authenticated_email text,
    request_uuid uuid
)
returns jsonb
language plpgsql
security definer
set search_path = pwa_v2, pg_catalog
as $$
declare
    invite_row pwa_v2.convites_conta%rowtype;
    target_profile_id uuid;
    display_name text;
begin
    if invite_token_hash is null or target_auth_user_id is null or authenticated_email is null then
        raise exception using errcode = '22023', message = 'Dados de convite incompletos';
    end if;

    select *
      into invite_row
      from pwa_v2.convites_conta
     where token_hash = invite_token_hash
     for update;

    if not found then
        raise exception using errcode = 'P0001', message = 'Convite inválido';
    end if;
    if invite_row.consumed_at is not null then
        raise exception using errcode = 'P0001', message = 'Convite já consumido';
    end if;
    if invite_row.valid_until <= now() then
        raise exception using errcode = 'P0001', message = 'Convite expirado';
    end if;
    if lower(btrim(invite_row.email_autorizado)) <> lower(btrim(authenticated_email)) then
        raise exception using errcode = 'P0001', message = 'E-mail não autorizado para este convite';
    end if;

    display_name := split_part(lower(btrim(authenticated_email)), '@', 1);
    select p.id
      into target_profile_id
      from pwa_v2.perfis as p
     where p.auth_user_id = target_auth_user_id
     for update;

    if target_profile_id is null then
        insert into pwa_v2.perfis (auth_user_id, nome, email, status)
        values (target_auth_user_id, display_name, lower(btrim(authenticated_email)), 'active')
        returning id into target_profile_id;
    else
        update pwa_v2.perfis
           set email = lower(btrim(authenticated_email)),
               status = 'active',
               updated_at = now()
         where id = target_profile_id;
    end if;

    insert into pwa_v2.vinculos_loja (perfil_id, loja_id, papel, status)
    values (target_profile_id, invite_row.loja_id, invite_row.papel, 'active')
    on conflict (perfil_id, loja_id, papel)
    do update set status = 'active', updated_at = now();

    update pwa_v2.convites_conta
       set consumed_at = now(), consumed_by_profile_id = target_profile_id
     where id = invite_row.id;

    insert into pwa_v2.auditoria (
        ator_perfil_id, acao, entidade_tipo, entidade_id, origem, request_id, metadata
    ) values (
        target_profile_id, 'invite_consumed', 'convites_conta', invite_row.id::text, 'bootstrap', request_uuid,
        jsonb_build_object('papel', invite_row.papel, 'loja_id', invite_row.loja_id)
    );

    return jsonb_build_object(
        'perfil_id', target_profile_id,
        'loja_id', invite_row.loja_id,
        'papel', invite_row.papel
    );
end
$$;

create or replace function pwa_private.bootstrap_admin(
    target_auth_user_id uuid,
    authenticated_email text,
    display_name text,
    request_uuid uuid
)
returns jsonb
language plpgsql
security definer
set search_path = pwa_v2, pg_catalog
as $$
declare
    target_profile_id uuid;
begin
    if target_auth_user_id is null or authenticated_email is null then
        raise exception using errcode = '22023', message = 'Dados do administrador incompletos';
    end if;
    if exists (
        select 1 from pwa_v2.vinculos_loja
         where loja_id is null and papel = 'admin' and status = 'active'
    ) then
        raise exception using errcode = 'P0001', message = 'Administrador inicial já configurado';
    end if;

    select p.id into target_profile_id
      from pwa_v2.perfis p
     where p.auth_user_id = target_auth_user_id
     for update;

    if target_profile_id is null then
        insert into pwa_v2.perfis (auth_user_id, nome, email, status)
        values (
            target_auth_user_id,
            coalesce(nullif(btrim(display_name), ''), split_part(lower(btrim(authenticated_email)), '@', 1)),
            lower(btrim(authenticated_email)),
            'active'
        )
        returning id into target_profile_id;
    else
        update pwa_v2.perfis
           set nome = coalesce(nullif(btrim(display_name), ''), nome),
               email = lower(btrim(authenticated_email)),
               status = 'active',
               updated_at = now()
         where id = target_profile_id;
    end if;

    insert into pwa_v2.vinculos_loja (perfil_id, loja_id, papel, status)
    values (target_profile_id, null, 'admin', 'active');

    insert into pwa_v2.auditoria (
        ator_perfil_id, acao, entidade_tipo, entidade_id, origem, request_id, metadata
    ) values (
        target_profile_id, 'admin_bootstrapped', 'perfis', target_profile_id::text, 'bootstrap', request_uuid, '{}'::jsonb
    );

    return jsonb_build_object('perfil_id', target_profile_id, 'papel', 'admin');
end
$$;

create or replace function pwa_private.touch_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
    new.updated_at = now();
    return new;
end
$$;

drop trigger if exists perfis_touch_updated_at on pwa_v2.perfis;
create trigger perfis_touch_updated_at
    before update on pwa_v2.perfis
    for each row execute function pwa_private.touch_updated_at();

drop trigger if exists lojas_touch_updated_at on pwa_v2.lojas;
create trigger lojas_touch_updated_at
    before update on pwa_v2.lojas
    for each row execute function pwa_private.touch_updated_at();

drop trigger if exists vinculos_touch_updated_at on pwa_v2.vinculos_loja;
create trigger vinculos_touch_updated_at
    before update on pwa_v2.vinculos_loja
    for each row execute function pwa_private.touch_updated_at();

drop trigger if exists eventos_touch_updated_at on pwa_v2.eventos;
create trigger eventos_touch_updated_at
    before update on pwa_v2.eventos
    for each row execute function pwa_private.touch_updated_at();

drop trigger if exists presencas_touch_updated_at on pwa_v2.solicitacoes_presenca;
create trigger presencas_touch_updated_at
    before update on pwa_v2.solicitacoes_presenca
    for each row execute function pwa_private.touch_updated_at();

drop trigger if exists publicacoes_touch_updated_at on pwa_v2.publicacoes_canal;
create trigger publicacoes_touch_updated_at
    before update on pwa_v2.publicacoes_canal
    for each row execute function pwa_private.touch_updated_at();

-- Wrapper exposto ao backend. A lógica privilegiada permanece no schema privado.
create or replace function pwa_v2.consume_invite(
    invite_token_hash text,
    target_auth_user_id uuid,
    authenticated_email text,
    request_uuid uuid
)
returns jsonb
language sql
security invoker
set search_path = pwa_v2, pg_catalog
as $$
    select pwa_private.consume_invite($1, $2, $3, $4)
$$;

create or replace function pwa_v2.bootstrap_admin(
    target_auth_user_id uuid,
    authenticated_email text,
    display_name text,
    request_uuid uuid
)
returns jsonb
language sql
security invoker
set search_path = pwa_v2, pg_catalog
as $$
    select pwa_private.bootstrap_admin($1, $2, $3, $4)
$$;

revoke all on function pwa_private.current_profile_id() from public, anon;
revoke all on function pwa_private.is_global_admin() from public, anon;
revoke all on function pwa_private.has_store_role(bigint, text[]) from public, anon;
revoke all on function pwa_private.consume_invite(text, uuid, text, uuid) from public, anon, authenticated;
revoke all on function pwa_private.bootstrap_admin(uuid, text, text, uuid) from public, anon, authenticated;
revoke all on function pwa_private.touch_updated_at() from public, anon, authenticated;
revoke all on function pwa_v2.consume_invite(text, uuid, text, uuid) from public, anon, authenticated;
revoke all on function pwa_v2.bootstrap_admin(uuid, text, text, uuid) from public, anon, authenticated;
grant execute on function pwa_private.current_profile_id() to authenticated, service_role;
grant execute on function pwa_private.is_global_admin() to authenticated, service_role;
grant execute on function pwa_private.has_store_role(bigint, text[]) to authenticated, service_role;
grant execute on function pwa_private.consume_invite(text, uuid, text, uuid) to service_role;
grant execute on function pwa_private.bootstrap_admin(uuid, text, text, uuid) to service_role;
grant execute on function pwa_v2.consume_invite(text, uuid, text, uuid) to service_role;
grant execute on function pwa_v2.bootstrap_admin(uuid, text, text, uuid) to service_role;

do $$
begin
    if to_regclass('storage.buckets') is not null then
        insert into storage.buckets (id, name, public)
        values ('pwa-private', 'pwa-private', false)
        on conflict (id) do update set public = false;
    end if;
end
$$;

-- RLS deve existir desde a criação. O backend com service_role aplica as mesmas
-- regras de negócio antes de qualquer mutação; o banco continua protegido contra
-- acesso direto entre lojas por sessões autenticadas.
alter table pwa_v2.perfis enable row level security;
alter table pwa_v2.identidades_externas enable row level security;
alter table pwa_v2.lojas enable row level security;
alter table pwa_v2.vinculos_loja enable row level security;
alter table pwa_v2.convites_conta enable row level security;
alter table pwa_v2.eventos enable row level security;
alter table pwa_v2.solicitacoes_presenca enable row level security;
alter table pwa_v2.publicacoes_canal enable row level security;
alter table pwa_v2.auditoria enable row level security;

alter table pwa_v2.perfis force row level security;
alter table pwa_v2.identidades_externas force row level security;
alter table pwa_v2.lojas force row level security;
alter table pwa_v2.vinculos_loja force row level security;
alter table pwa_v2.convites_conta force row level security;
alter table pwa_v2.eventos force row level security;
alter table pwa_v2.solicitacoes_presenca force row level security;
alter table pwa_v2.publicacoes_canal force row level security;
alter table pwa_v2.auditoria force row level security;

drop policy if exists perfis_select_own_or_global on pwa_v2.perfis;
create policy perfis_select_own_or_global on pwa_v2.perfis
    for select to authenticated
    using (auth_user_id = auth.uid() or pwa_private.is_global_admin());

drop policy if exists perfis_update_own on pwa_v2.perfis;
create policy perfis_update_own on pwa_v2.perfis
    for update to authenticated
    using (auth_user_id = auth.uid())
    with check (auth_user_id = auth.uid());

drop policy if exists identidades_select_own_or_global on pwa_v2.identidades_externas;
create policy identidades_select_own_or_global on pwa_v2.identidades_externas
    for select to authenticated
    using (
        perfil_id = pwa_private.current_profile_id()
        or pwa_private.is_global_admin()
    );

drop policy if exists lojas_select_linked on pwa_v2.lojas;
create policy lojas_select_linked on pwa_v2.lojas
    for select to authenticated
    using (pwa_private.has_store_role(id, array['member', 'secretary', 'admin']::text[]));

drop policy if exists lojas_insert_global on pwa_v2.lojas;
create policy lojas_insert_global on pwa_v2.lojas
    for insert to authenticated
    with check (pwa_private.is_global_admin());

drop policy if exists lojas_update_global on pwa_v2.lojas;
create policy lojas_update_global on pwa_v2.lojas
    for update to authenticated
    using (pwa_private.is_global_admin())
    with check (pwa_private.is_global_admin());

drop policy if exists lojas_delete_global on pwa_v2.lojas;
create policy lojas_delete_global on pwa_v2.lojas
    for delete to authenticated
    using (pwa_private.is_global_admin());

drop policy if exists vinculos_select_self_or_admin on pwa_v2.vinculos_loja;
create policy vinculos_select_self_or_admin on pwa_v2.vinculos_loja
    for select to authenticated
    using (
        perfil_id = pwa_private.current_profile_id()
        or pwa_private.is_global_admin()
        or pwa_private.has_store_role(loja_id, array['admin']::text[])
    );

drop policy if exists eventos_select_linked on pwa_v2.eventos;
create policy eventos_select_linked on pwa_v2.eventos
    for select to authenticated
    using (pwa_private.has_store_role(loja_id, array['member', 'secretary', 'admin']::text[]));

drop policy if exists eventos_insert_manager on pwa_v2.eventos;
create policy eventos_insert_manager on pwa_v2.eventos
    for insert to authenticated
    with check (
        pwa_private.has_store_role(loja_id, array['secretary', 'admin']::text[])
        and criado_por_id = pwa_private.current_profile_id()
    );

drop policy if exists eventos_update_manager on pwa_v2.eventos;
create policy eventos_update_manager on pwa_v2.eventos
    for update to authenticated
    using (pwa_private.has_store_role(loja_id, array['secretary', 'admin']::text[]))
    with check (pwa_private.has_store_role(loja_id, array['secretary', 'admin']::text[]));

drop policy if exists eventos_delete_manager on pwa_v2.eventos;
create policy eventos_delete_manager on pwa_v2.eventos
    for delete to authenticated
    using (pwa_private.has_store_role(loja_id, array['secretary', 'admin']::text[]));

drop policy if exists presencas_select_manager on pwa_v2.solicitacoes_presenca;
create policy presencas_select_manager on pwa_v2.solicitacoes_presenca
    for select to authenticated
    using (
        exists (
            select 1 from pwa_v2.eventos e
             where e.id = evento_id
               and pwa_private.has_store_role(e.loja_id, array['secretary', 'admin']::text[])
        )
    );

drop policy if exists presencas_update_manager on pwa_v2.solicitacoes_presenca;
create policy presencas_update_manager on pwa_v2.solicitacoes_presenca
    for update to authenticated
    using (
        exists (
            select 1 from pwa_v2.eventos e
             where e.id = evento_id
               and pwa_private.has_store_role(e.loja_id, array['secretary', 'admin']::text[])
        )
    )
    with check (
        exists (
            select 1 from pwa_v2.eventos e
             where e.id = evento_id
               and pwa_private.has_store_role(e.loja_id, array['secretary', 'admin']::text[])
        )
    );

drop policy if exists publicacoes_select_linked on pwa_v2.publicacoes_canal;
create policy publicacoes_select_linked on pwa_v2.publicacoes_canal
    for select to authenticated
    using (
        exists (
            select 1 from pwa_v2.eventos e
             where e.id = evento_id
               and pwa_private.has_store_role(e.loja_id, array['member', 'secretary', 'admin']::text[])
        )
    );

drop policy if exists auditoria_select_global on pwa_v2.auditoria;
create policy auditoria_select_global on pwa_v2.auditoria
    for select to authenticated
    using (pwa_private.is_global_admin());

-- Somente o backend recebe privilégios mutáveis. O navegador autentica via Auth,
-- mas não recebe service_role nem acesso direto de escrita ao schema operacional.
revoke all on all tables in schema pwa_v2 from public, anon, authenticated, service_role;
grant select on pwa_v2.perfis, pwa_v2.identidades_externas, pwa_v2.lojas,
    pwa_v2.vinculos_loja, pwa_v2.eventos, pwa_v2.solicitacoes_presenca,
    pwa_v2.publicacoes_canal, pwa_v2.auditoria to authenticated;
grant all privileges on all tables in schema pwa_v2 to service_role;
grant usage, select on all sequences in schema pwa_v2 to service_role;

-- Não há exposição direta anônima das tabelas. O endpoint público valida o token,
-- aplica rate limit/honeypot e usa uma operação de backend limitada.
